mutation UpdateUser($userId: Float!, $data: UserUpdateInput!) {
  updateUser(userId: $userId, data: $data) {
    description
    image
    hashedPassword
    xp
    friends {
      id
    }
  }
}

mutation UpdateUser($userId: Float!, $nickName: String, $description: String) {
  updateUser(userId: $userId, data: { nickName: $nickName, description: $description }) {
    description
    image
    hashedPassword
    xp
    friends {
      id
    }
  }
}
